title: 'lovata.youvegotmail::lang.title.mallings_list'
modelClass: Lovata\YouVeGotMail\Models\Mailing
list: $/lovata/youvegotmail/models/mailing/columns.yaml
recordUrl: 'lovata/youvegotmail/mailings/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '25'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: id
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
